kind: pipeline
name: default

type: docker
steps:
  - name: lint
    image: golangci/golangci-lint
    commands:
      - golangci-lint run --enable-all
  - name: test
    image: golang
    commands:
      - go test -v ./... -covermode=count -coverprofile=coverage.out
  - name: coveralls
    image: lizheming/drone-coveralls
    settings:
      token:
        from_secret: coveralls_token
      files:
        - ./coverage.out